USE [A2ZHRMCUS]
GO

ALTER TABLE A2ZHRMCUS..A2ZEMPLOYEE ADD  EmpCashCode int

ALTER TABLE A2ZHRMCUS..A2ZHRPOSTING ADD  EmpOldCashCode int
ALTER TABLE A2ZHRMCUS..A2ZHRPOSTING ADD  EmpNewCashCode int

ALTER TABLE A2ZHRMCUS..A2ZHRPROMOTION ADD  EmpOldCashCode int
ALTER TABLE A2ZHRMCUS..A2ZHRPROMOTION ADD  EmpNewCashCode int



