USE [A2ZCSMCUS]
GO

ALTER TABLE A2ZCSMCUS..A2ZTRANSACTION ADD  AccTypeMode tinyint

ALTER TABLE A2ZCSMCUS..WF_TRANSACTION ADD  AccTypeMode tinyint

ALTER TABLE A2ZCSMCUST2015..A2ZTRANSACTION ADD  AccTypeMode tinyint

ALTER TABLE A2ZCSMCUST2016..A2ZTRANSACTION ADD  AccTypeMode tinyint

