USE [A2ZCSMCUS]
GO

ALTER TABLE A2ZCSMCUS..A2ZSYSIDS ADD  IdsCWarehouseFlag bit

go

ALTER TABLE A2ZGLMCUS..A2ZSYSIDS ADD  IdsCWarehouseFlag bit

GO

ALTER TABLE A2ZBTMCUS..A2ZSYSIDS ADD  IdsCWarehouseFlag bit

GO 

ALTER TABLE A2ZHRMCUS..A2ZSYSIDS ADD  IdsCWarehouseFlag bit

GO 

ALTER TABLE A2ZHKMCUS..A2ZSYSIDS ADD  IdsCWarehouseFlag bit

GO

ALTER TABLE A2ZSTMCUS..A2ZSYSIDS ADD  IdsCWarehouseFlag bit



