
truncate table A2ZCSMCUS..A2ZUSERCASHCODE

INSERT INTO A2ZCSMCUS..A2ZUSERCASHCODE(IdsNo,FromCashCode)
SELECT IdsNo,GLCashCode 
FROM A2ZCSMCUS..A2ZSYSIDS;


UPDATE A2ZCSMCUS..A2ZUSERCASHCODE SET  A2ZCSMCUS..A2ZUSERCASHCODE.FromCashCodeDesc = (SELECT A2ZGLMCUS..A2ZCGLMST.GLAccDesc 
FROM A2ZGLMCUS..A2ZCGLMST
WHERE A2ZCSMCUS..A2ZUSERCASHCODE.FromCashCode=A2ZGLMCUS..A2ZCGLMST.GLAccNo);

