USE [A2ZCSMCUS]
GO



ALTER TABLE A2ZCSMCUS..A2ZTRANSACTION ADD ReTrnId int

ALTER TABLE A2ZCSMCUS..A2ZTRANSACTION ADD ReTrnDate datetime

ALTER TABLE A2ZCSMCUST2015..A2ZTRANSACTION ADD ReTrnId int

ALTER TABLE A2ZCSMCUST2015..A2ZTRANSACTION ADD ReTrnDate datetime

ALTER TABLE A2ZCSMCUST2016..A2ZTRANSACTION ADD ReTrnId int

ALTER TABLE A2ZCSMCUST2016..A2ZTRANSACTION ADD ReTrnDate datetime

ALTER TABLE A2ZCSMCUST2017..A2ZTRANSACTION ADD ReTrnId int

ALTER TABLE A2ZCSMCUST2017..A2ZTRANSACTION ADD ReTrnDate datetime