USE [A2ZCSMCUS]
GO

/****** Object:  StoredProcedure [dbo].[Sp_CSWFGurantorInformation]    Script Date: 03/18/2018 1:09:42 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO





CREATE PROCEDURE [dbo].[Sp_CSWFGurantorInformation] (@CuType smallint, @CuNo INT, @MemNo INT, @AccType INT, @AccNo bigint)

AS
BEGIN 

/*

EXECUTE Sp_CSWFGurantorInformation 3,538,0,0,0
EXECUTE Sp_CSWFGurantorInformation 3,562,0,0,0

*/


	DECLARE @strSQL NVARCHAR(MAX);
	DECLARE @AccNumber  Bigint;
	DECLARE @AccLoanSancAmt money;

	TRUNCATE TABLE WFGRNINFORMATIONRPT;


	INSERT INTO WFGRNINFORMATIONRPT ([LoanApplicationNo],[GurAccLeanAmount],[GurAccNo])
	SELECT [LoanApplicationNo],[PrAmount],[PrName]
	FROM [A2ZPRGUAR]
	WHERE A2ZPRGUAR.AccStat < 90;

	UPDATE WFGRNINFORMATIONRPT SET WFGRNINFORMATIONRPT.AccNo = (SELECT A2ZACCOUNT.AccNo FROM A2ZACCOUNT
	WHERE WFGRNINFORMATIONRPT.LoanApplicationNo = A2ZACCOUNT.AccLoanAppNo)
	FROM WFGRNINFORMATIONRPT,A2ZACCOUNT;

	UPDATE WFGRNINFORMATIONRPT SET WFGRNINFORMATIONRPT.CuType = (SELECT A2ZACCOUNT.CuType FROM A2ZACCOUNT
	WHERE WFGRNINFORMATIONRPT.AccNo = A2ZACCOUNT.AccNo)
	FROM WFGRNINFORMATIONRPT,A2ZACCOUNT;

	UPDATE WFGRNINFORMATIONRPT SET WFGRNINFORMATIONRPT.CuNo = (SELECT A2ZACCOUNT.CuNo FROM A2ZACCOUNT
	WHERE WFGRNINFORMATIONRPT.AccNo = A2ZACCOUNT.AccNo)
	FROM WFGRNINFORMATIONRPT,A2ZACCOUNT;

	UPDATE WFGRNINFORMATIONRPT SET WFGRNINFORMATIONRPT.MemNo = (SELECT A2ZACCOUNT.MemNo FROM A2ZACCOUNT
	WHERE WFGRNINFORMATIONRPT.AccNo = A2ZACCOUNT.AccNo)
	FROM WFGRNINFORMATIONRPT,A2ZACCOUNT;

	INSERT INTO WFGRNINFORMATIONRPT ([CuType],[CuNo],[MemNo],[AccType],[GurAccNo],[LoanApplicationNo],[GurAccLeanAmount],[AccNo])
	SELECT [CuType],[CuNo],[MemNo],[AccType],[AccNo],[LoanApplicationNo],[AccAmount],[LoanAccNo]
	FROM [A2ZACGUAR]
	WHERE A2ZACGUAR.AccStat < 90;

	INSERT INTO WFGRNINFORMATIONRPT ([CuType],[CuNo],[MemNo],[AccType],[GurAccNo],[LoanApplicationNo],[GurAccLeanAmount],[AccNo])
	SELECT [CuType],[CuNo],[MemNo],[AccType],[AccNo],[LoanApplicationNo],[AccAmount],[LoanAccNo]
	FROM [A2ZSHGUAR]
	WHERE A2ZSHGUAR.AccStat < 90;

	UPDATE WFGRNINFORMATIONRPT SET WFGRNINFORMATIONRPT.AccType = LEFT(AccNo,2);

	DELETE FROM WFGRNINFORMATIONRPT WHERE AccType IS NULL;

	UPDATE WFGRNINFORMATIONRPT SET CuName = (SELECT CuName FROM A2ZCUNION WHERE 
	WFGRNINFORMATIONRPT.CuType = A2ZCUNION.CuType AND WFGRNINFORMATIONRPT.CuNo = A2ZCUNION.CuNo);

	UPDATE WFGRNINFORMATIONRPT SET MemName = (SELECT MemName FROM A2ZMEMBER WHERE 
	WFGRNINFORMATIONRPT.CuType = A2ZMEMBER.CuType AND WFGRNINFORMATIONRPT.CuNo = A2ZMEMBER.CuNo AND
	WFGRNINFORMATIONRPT.MemNo = A2ZMEMBER.MemNo);

	UPDATE WFGRNINFORMATIONRPT SET WFGRNINFORMATIONRPT.AccBalance = (SELECT A2ZACCOUNT.AccBalance FROM A2ZACCOUNT
	WHERE WFGRNINFORMATIONRPT.AccNo = A2ZACCOUNT.AccNo)
	FROM WFGRNINFORMATIONRPT,A2ZACCOUNT;

	--UPDATE WFGRNINFORMATIONRPT SET WFGRNINFORMATIONRPT.AccLoanSancAmt = (SELECT A2ZACCOUNT.AccLoanSancAmt FROM A2ZACCOUNT
	--WHERE WFGRNINFORMATIONRPT.AccNo = A2ZACCOUNT.AccNo)
	--FROM WFGRNINFORMATIONRPT,A2ZACCOUNT;


	UPDATE WFGRNINFORMATIONRPT SET WFGRNINFORMATIONRPT.AccLoanSancAmt = (SELECT A2ZACCOUNT.AccLoanSancAmt FROM A2ZACCOUNT
    WHERE A2ZACCOUNT.AccNo = WFGRNINFORMATIONRPT.AccNo)
    FROM WFGRNINFORMATIONRPT,A2ZACCOUNT 
    WHERE WFGRNINFORMATIONRPT.Id IN
    (SELECT MIN(WFGRNINFORMATIONRPT.Id) FROM WFGRNINFORMATIONRPT GROUP BY WFGRNINFORMATIONRPT.AccNo)



	
	UPDATE WFGRNINFORMATIONRPT SET WFGRNINFORMATIONRPT.GurAccAmount = (SELECT A2ZACCOUNT.AccBalance FROM A2ZACCOUNT
	WHERE WFGRNINFORMATIONRPT.GurAccNo = A2ZACCOUNT.AccNo AND
	ISNUMERIC(WFGRNINFORMATIONRPT.GurAccNo) > 0)
	FROM WFGRNINFORMATIONRPT,A2ZACCOUNT;

	UPDATE WFGRNINFORMATIONRPT SET WFGRNINFORMATIONRPT.AccStatus = (SELECT A2ZACCOUNT.AccStatus FROM A2ZACCOUNT
	WHERE WFGRNINFORMATIONRPT.AccNo = A2ZACCOUNT.AccNo)
	FROM WFGRNINFORMATIONRPT,A2ZACCOUNT;

	DELETE WFGRNINFORMATIONRPT WHERE AccStatus = 98 OR AccStatus = 99;

	UPDATE WFGRNINFORMATIONRPT SET AccTypeDescription = (SELECT A2ZACCTYPE.AccTypeDescription FROM A2ZACCTYPE
	WHERE WFGRNINFORMATIONRPT.AccType = A2ZACCTYPE.AccTypeCode);

	UPDATE WFGRNINFORMATIONRPT SET SortFlag = 0;

	UPDATE WFGRNINFORMATIONRPT SET SortFlag = 99 WHERE NOT ISNUMERIC(WFGRNINFORMATIONRPT.GurAccNo) <> 0;
	UPDATE WFGRNINFORMATIONRPT SET GurAccAmount = 0 WHERE  GurAccAmount IS NULL;
	UPDATE WFGRNINFORMATIONRPT SET AccBalance = 0 WHERE  AccBalance IS NULL;

	UPDATE WFGRNINFORMATIONRPT SET WFGRNINFORMATIONRPT.AccLoanSancAmt = 0
	WHERE  WFGRNINFORMATIONRPT.GurAccAmount > 0 AND AccType < 50;
	 
	UPDATE WFGRNINFORMATIONRPT SET WFGRNINFORMATIONRPT.AccLoanSancAmt = 0
	WHERE  WFGRNINFORMATIONRPT.SortFlag =99; 

	IF  @CuType <> 0
		BEGIN
			DELETE WFGRNINFORMATIONRPT WHERE CuType <> @CuType; 
		END                   
                      
	IF  @CuNo <> 0
		BEGIN
			DELETE WFGRNINFORMATIONRPT WHERE CuNo <> @CuNo; 
		END    
    
	IF  @MemNo <> 99999
		BEGIN
			DELETE WFGRNINFORMATIONRPT WHERE MemNo <> @MemNo;
		END 
				   
	IF  @AccType <> 0
		BEGIN
			DELETE WFGRNINFORMATIONRPT WHERE AccType <> @AccType;
		END	   
				     
	IF  @AccNo <> 0
		BEGIN
			DELETE WFGRNINFORMATIONRPT WHERE AccNo <> @AccNo;
		END	


    

	SELECT * FROM WFGRNINFORMATIONRPT;
END




GO

