USE A2ZHRMCUS
GO

CREATE PROCEDURE [dbo].[Sp_HRGenerateEmployeeSettlement] (@EmpCode INT, @nFlag INT)  

AS
BEGIN

--
-- Last Modified Date on June 24, 2019
--
-- Sp_HRGenerateEmployeeSettlement 403,0
--

	TRUNCATE TABLE WFSETTLEMENT;

	CREATE TABLE #TMPENCASHMENI(
	[AccountHead] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Amount] [money] NULL DEFAULT ((0)),
	[Flag] [int] NULL DEFAULT ((0)),
	[GLCodeDr] [int] NULL DEFAULT ((0)),
	[GLCodeCr] [int] NULL DEFAULT ((0)),
	[AccNo] [bigint] NULL DEFAULT ((0)),
	[ShowInterest] [int] NULL DEFAULT ((0)),
	[TrnInterestAmt] [money] NULL DEFAULT ((0)));
	

	DECLARE @ProcessDate SMALLDATETIME;

	SET @ProcessDate = (SELECT ProcessDate FROM A2ZCSMCUS..A2ZCSPARAMETER);

-- Generate Benefits -----

	INSERT INTO #TMPENCASHMENI(AccountHead,Flag,GLCodeDr,GLCodeCr) VALUES('Security Deposit',1,20602001,0);

	INSERT INTO #TMPENCASHMENI(AccountHead,Flag,GLCodeDr,GLCodeCr) VALUES('Provident Fund Office',1,20307001,0);

	INSERT INTO #TMPENCASHMENI(AccountHead,Flag,GLCodeDr,GLCodeCr) VALUES('Provident Fund Own',1,10606013,0);

	INSERT INTO #TMPENCASHMENI(AccountHead,Flag,GLCodeDr,GLCodeCr) VALUES('Provident Fund Interest',1,10606013,0);

	INSERT INTO #TMPENCASHMENI(AccountHead,Flag,GLCodeDr,GLCodeCr) VALUES('Gratuity Amount',1,20308001,0);

	INSERT INTO #TMPENCASHMENI(AccountHead,Flag,GLCodeDr,GLCodeCr) VALUES('Earn Leave',1,50201001,0);

	INSERT INTO #TMPENCASHMENI(AccountHead,Flag,GLCodeDr,GLCodeCr) VALUES('Salary Due',1,50201001,0);

	INSERT INTO #TMPENCASHMENI(AccountHead,Flag,GLCodeDr,GLCodeCr) VALUES('Insurance Claim',1,20603005,0);

	INSERT INTO #TMPENCASHMENI(AccountHead,Flag,GLCodeDr,GLCodeCr) VALUES('Staff CU Deposit',1,20604006,0);

	INSERT INTO #TMPENCASHMENI(AccountHead,Flag,GLCodeDr,GLCodeCr) VALUES('Others Benefits',1,50201001,0);

-- End of Generate Benefits -----

-- Generate Deduction -----

	INSERT INTO #TMPENCASHMENI(AccountHead,Flag,GLCodeDr,GLCodeCr) VALUES('Services Loan',2,0,10504001);

	INSERT INTO #TMPENCASHMENI(AccountHead,Flag,GLCodeDr,GLCodeCr) VALUES('Motor Cycle Loan',2,0,10504002);

	INSERT INTO #TMPENCASHMENI(AccountHead,Flag,GLCodeDr,GLCodeCr) VALUES('By Cycle Loan',2,0,10504003);

	INSERT INTO #TMPENCASHMENI(AccountHead,Flag,GLCodeDr,GLCodeCr) VALUES('Computer Loan',2,0,10504004);

	INSERT INTO #TMPENCASHMENI(AccountHead,Flag,GLCodeDr,GLCodeCr) VALUES('PF Loan Principal',2,0,20312002);

	INSERT INTO #TMPENCASHMENI(AccountHead,Flag,GLCodeDr,GLCodeCr) VALUES('PF Loan Interest',2,0,20312002);

	INSERT INTO #TMPENCASHMENI(AccountHead,Flag,GLCodeDr,GLCodeCr) VALUES('EDU Loan Principal',2,0,10504007);

	INSERT INTO #TMPENCASHMENI(AccountHead,Flag,GLCodeDr,GLCodeCr) VALUES('EDU Loan Interest',2,0,40102004);

	INSERT INTO #TMPENCASHMENI(AccountHead,Flag,GLCodeDr,GLCodeCr) VALUES('STAFF CU Loan',2,0,20604006);

	INSERT INTO #TMPENCASHMENI(AccountHead,Flag,GLCodeDr,GLCodeCr) VALUES('Tax',2,0,20603004);

	INSERT INTO #TMPENCASHMENI(AccountHead,Flag,GLCodeDr,GLCodeCr) VALUES('Salary Adjustment',2,0,20702003);

	INSERT INTO #TMPENCASHMENI(AccountHead,Flag,GLCodeDr,GLCodeCr) VALUES('Others Deduction',2,0,20702003);

-- End of Generate Deduction -----

	UPDATE #TMPENCASHMENI SET #TMPENCASHMENI.Amount = A2ZCSMCUS..A2ZACCOUNT.AccTodaysOpBalance,#TMPENCASHMENI.AccNo = A2ZCSMCUS..A2ZACCOUNT.AccNo
	FROM #TMPENCASHMENI,A2ZCSMCUS..A2ZACCOUNT
	WHERE A2ZCSMCUS..A2ZACCOUNT.AccType = 19 AND A2ZCSMCUS..A2ZACCOUNT.CUNO = 0 AND 
	A2ZCSMCUS..A2ZACCOUNT.MEMNO = @EmpCode AND #TMPENCASHMENI.AccountHead = 'Security Deposit';

	UPDATE #TMPENCASHMENI SET #TMPENCASHMENI.Amount = (A2ZCSMCUS..A2ZACCOUNT.AccTodaysOpBalance / 2),#TMPENCASHMENI.AccNo = A2ZCSMCUS..A2ZACCOUNT.AccNo
	FROM #TMPENCASHMENI,A2ZCSMCUS..A2ZACCOUNT
	WHERE A2ZCSMCUS..A2ZACCOUNT.AccType = 26 AND A2ZCSMCUS..A2ZACCOUNT.CUNO = 0 AND 
	A2ZCSMCUS..A2ZACCOUNT.MEMNO = @EmpCode AND #TMPENCASHMENI.AccountHead = 'Provident Fund Office';

	UPDATE #TMPENCASHMENI SET #TMPENCASHMENI.Amount = (A2ZCSMCUS..A2ZACCOUNT.AccTodaysOpBalance / 2),#TMPENCASHMENI.AccNo = A2ZCSMCUS..A2ZACCOUNT.AccNo
	FROM #TMPENCASHMENI,A2ZCSMCUS..A2ZACCOUNT
	WHERE A2ZCSMCUS..A2ZACCOUNT.AccType = 26 AND A2ZCSMCUS..A2ZACCOUNT.CUNO = 0 AND 
	A2ZCSMCUS..A2ZACCOUNT.MEMNO = @EmpCode AND #TMPENCASHMENI.AccountHead = 'Provident Fund Own';

------ Gratuity Amount Calculate ----

	SELECT EmpCode,EmpName,EmpBaseGrade,EmpGrade,EmpPayLabel,EmpPerDate INTO #TEMPA2ZEMPLOYEE
	FROM A2ZHRMCUS..A2ZEMPLOYEE
	WHERE EmpCode = @EmpCode AND Status = 1 AND EmpServiceType = 1

	ALTER TABLE #TEMPA2ZEMPLOYEE ADD JobYear INT
	ALTER TABLE #TEMPA2ZEMPLOYEE ADD Basic MONEY
	ALTER TABLE #TEMPA2ZEMPLOYEE ADD Gratuity MONEY

	UPDATE #TEMPA2ZEMPLOYEE SET JobYear = (SELECT DATEDIFF(Month, EmpPerDate,@ProcessDate) AS DateDiff)/12; 

	DELETE FROM #TEMPA2ZEMPLOYEE WHERE JobYear < 5

	UPDATE #TEMPA2ZEMPLOYEE SET Basic = ((Bar1 * (EmpPayLabel-1)) + StartBasic)
	FROM A2ZHRMCUS..A2ZPAYSCALE,A2ZHRMCUS..#TEMPA2ZEMPLOYEE
	WHERE A2ZHRMCUS..A2ZPAYSCALE.Base = A2ZHRMCUS..#TEMPA2ZEMPLOYEE.EmpBaseGrade AND 
	A2ZHRMCUS..A2ZPAYSCALE.Payscale = A2ZHRMCUS..#TEMPA2ZEMPLOYEE.EmpGrade;

	UPDATE #TEMPA2ZEMPLOYEE SET Gratuity = (Basic * JobYear) WHERE JobYear < 11;

	UPDATE #TEMPA2ZEMPLOYEE SET Gratuity = (Basic * 10) WHERE JobYear > 10;

	UPDATE #TEMPA2ZEMPLOYEE SET Gratuity = Gratuity + ((Basic*2) * (JobYear -10)) WHERE JobYear BETWEEN 11 AND 20;

	UPDATE #TEMPA2ZEMPLOYEE SET Gratuity = Gratuity + ((Basic*2) * 10) WHERE JobYear BETWEEN 21 AND 35;

	UPDATE #TEMPA2ZEMPLOYEE SET Gratuity = Gratuity + ((Basic*3) * (JobYear - 20)) WHERE JobYear BETWEEN 21 AND 35;

	UPDATE #TMPENCASHMENI SET #TMPENCASHMENI.Amount = #TEMPA2ZEMPLOYEE.Gratuity
	FROM #TMPENCASHMENI,#TEMPA2ZEMPLOYEE
	WHERE #TEMPA2ZEMPLOYEE.EmpCode = @EmpCode AND #TMPENCASHMENI.AccountHead = 'Gratuity Amount';

	DROP TABLE #TEMPA2ZEMPLOYEE;

------ End of Gratuity Amount Calculate ----

------
	UPDATE #TMPENCASHMENI SET #TMPENCASHMENI.Amount = ABS(A2ZCSMCUS..A2ZACCOUNT.AccTodaysOpBalance),#TMPENCASHMENI.AccNo = A2ZCSMCUS..A2ZACCOUNT.AccNo
	FROM #TMPENCASHMENI,A2ZCSMCUS..A2ZACCOUNT
	WHERE A2ZCSMCUS..A2ZACCOUNT.AccType = 55 AND A2ZCSMCUS..A2ZACCOUNT.CUNO = 0 AND A2ZCSMCUS..A2ZACCOUNT.MEMNO = @EmpCode
	AND A2ZCSMCUS..A2ZACCOUNT.AccTodaysOpBalance < 0 AND #TMPENCASHMENI.AccountHead = 'Services Loan';

	UPDATE #TMPENCASHMENI SET #TMPENCASHMENI.Amount = ABS(A2ZCSMCUS..A2ZACCOUNT.AccTodaysOpBalance),#TMPENCASHMENI.AccNo = A2ZCSMCUS..A2ZACCOUNT.AccNo
	FROM #TMPENCASHMENI,A2ZCSMCUS..A2ZACCOUNT
	WHERE A2ZCSMCUS..A2ZACCOUNT.AccType = 56 AND A2ZCSMCUS..A2ZACCOUNT.CUNO = 0 AND A2ZCSMCUS..A2ZACCOUNT.MEMNO = @EmpCode
	AND A2ZCSMCUS..A2ZACCOUNT.AccTodaysOpBalance < 0 AND #TMPENCASHMENI.AccountHead = 'Motor Cycle Loan';

	UPDATE #TMPENCASHMENI SET #TMPENCASHMENI.Amount = ABS(A2ZCSMCUS..A2ZACCOUNT.AccTodaysOpBalance),#TMPENCASHMENI.AccNo = A2ZCSMCUS..A2ZACCOUNT.AccNo
	FROM #TMPENCASHMENI,A2ZCSMCUS..A2ZACCOUNT
	WHERE A2ZCSMCUS..A2ZACCOUNT.AccType = 57 AND A2ZCSMCUS..A2ZACCOUNT.CUNO = 0 AND A2ZCSMCUS..A2ZACCOUNT.MEMNO = @EmpCode
	AND A2ZCSMCUS..A2ZACCOUNT.AccTodaysOpBalance < 0 AND #TMPENCASHMENI.AccountHead = 'By Cycle Loan';

	UPDATE #TMPENCASHMENI SET #TMPENCASHMENI.Amount = ABS(A2ZCSMCUS..A2ZACCOUNT.AccTodaysOpBalance),#TMPENCASHMENI.AccNo = A2ZCSMCUS..A2ZACCOUNT.AccNo
	FROM #TMPENCASHMENI,A2ZCSMCUS..A2ZACCOUNT
	WHERE A2ZCSMCUS..A2ZACCOUNT.AccType = 58 AND A2ZCSMCUS..A2ZACCOUNT.CUNO = 0 AND A2ZCSMCUS..A2ZACCOUNT.MEMNO = @EmpCode
	AND A2ZCSMCUS..A2ZACCOUNT.AccTodaysOpBalance < 0 AND #TMPENCASHMENI.AccountHead = 'Computer Loan';

	UPDATE #TMPENCASHMENI SET #TMPENCASHMENI.Amount = ABS(A2ZCSMCUS..A2ZACCOUNT.AccTodaysOpBalance),#TMPENCASHMENI.AccNo = A2ZCSMCUS..A2ZACCOUNT.AccNo,
	#TMPENCASHMENI.TrnInterestAmt = ABS(A2ZCSMCUS..A2ZACCOUNT.AccTodaysOpBalance * 12 /1200)
	FROM #TMPENCASHMENI,A2ZCSMCUS..A2ZACCOUNT
	WHERE A2ZCSMCUS..A2ZACCOUNT.AccType = 63 AND A2ZCSMCUS..A2ZACCOUNT.CUNO = 0 AND A2ZCSMCUS..A2ZACCOUNT.MEMNO = @EmpCode
	AND A2ZCSMCUS..A2ZACCOUNT.AccTodaysOpBalance < 0 AND #TMPENCASHMENI.AccountHead = 'PF Loan Principal';

	UPDATE #TMPENCASHMENI SET #TMPENCASHMENI.Amount = ABS(A2ZCSMCUS..A2ZACCOUNT.AccTodaysOpBalance * 12 /1200),#TMPENCASHMENI.AccNo = A2ZCSMCUS..A2ZACCOUNT.AccNo,
	#TMPENCASHMENI.ShowInterest = 1
	FROM #TMPENCASHMENI,A2ZCSMCUS..A2ZACCOUNT
	WHERE A2ZCSMCUS..A2ZACCOUNT.AccType = 63 AND A2ZCSMCUS..A2ZACCOUNT.CUNO = 0 AND A2ZCSMCUS..A2ZACCOUNT.MEMNO = @EmpCode
	AND A2ZCSMCUS..A2ZACCOUNT.AccTodaysOpBalance < 0 AND #TMPENCASHMENI.AccountHead = 'PF Loan Interest';

	UPDATE #TMPENCASHMENI SET #TMPENCASHMENI.Amount = ABS(A2ZCSMCUS..A2ZACCOUNT.AccTodaysOpBalance),#TMPENCASHMENI.AccNo = A2ZCSMCUS..A2ZACCOUNT.AccNo,
	#TMPENCASHMENI.TrnInterestAmt = ABS(A2ZCSMCUS..A2ZACCOUNT.AccTodaysOpBalance * 12 /1200)
	FROM #TMPENCASHMENI,A2ZCSMCUS..A2ZACCOUNT
	WHERE A2ZCSMCUS..A2ZACCOUNT.AccType = 65 AND A2ZCSMCUS..A2ZACCOUNT.CUNO = 0 AND A2ZCSMCUS..A2ZACCOUNT.MEMNO = @EmpCode
	AND A2ZCSMCUS..A2ZACCOUNT.AccTodaysOpBalance < 0 AND #TMPENCASHMENI.AccountHead = 'EDU Loan Principal'

	UPDATE #TMPENCASHMENI SET #TMPENCASHMENI.Amount = ABS(A2ZCSMCUS..A2ZACCOUNT.AccTodaysOpBalance * 12 /1200),#TMPENCASHMENI.AccNo = A2ZCSMCUS..A2ZACCOUNT.AccNo,
	#TMPENCASHMENI.ShowInterest = 1
	FROM #TMPENCASHMENI,A2ZCSMCUS..A2ZACCOUNT
	WHERE A2ZCSMCUS..A2ZACCOUNT.AccType = 65 AND A2ZCSMCUS..A2ZACCOUNT.CUNO = 0 AND A2ZCSMCUS..A2ZACCOUNT.MEMNO = @EmpCode
	AND A2ZCSMCUS..A2ZACCOUNT.AccTodaysOpBalance < 0 AND #TMPENCASHMENI.AccountHead = 'EDU Loan Interest';

	--SELECT * FROM #TMPENCASHMENI;

	INSERT INTO WFSETTLEMENT (EmpCode,AccountHead,Amount,Flag,GLCodeDr,GLCodeCr,AccNo,ShowInterest,TrnInterestAmt)
	SELECT @EmpCode,AccountHead,Amount,Flag,GLCodeDr,GLCodeCr,AccNo,ShowInterest,TrnInterestAmt FROM #TMPENCASHMENI;

	DROP TABLE #TMPENCASHMENI;

	UPDATE WFSETTLEMENT SET WFSETTLEMENT.GLAccDesc = (SELECT A2ZCGLMST.GLAccDesc FROM A2ZGLMCUS..A2ZCGLMST
	WHERE WFSETTLEMENT.GLCodeDr = A2ZCGLMST.GLAccNo)
	WHERE WFSETTLEMENT.GLCodeDr > 0;

	UPDATE WFSETTLEMENT SET WFSETTLEMENT.GLAccDesc = (SELECT A2ZCGLMST.GLAccDesc FROM A2ZGLMCUS..A2ZCGLMST
	WHERE WFSETTLEMENT.GLCodeCr = A2ZCGLMST.GLAccNo)
	WHERE WFSETTLEMENT.GLCodeCr > 0;

END



