USE [A2ZSTMCUS]
GO

/****** Object:  StoredProcedure [dbo].[SpM_STCorrectionTransactionAvg]    Script Date: 06/27/2019 4:43:50 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO









CREATE PROCEDURE [dbo].[SpM_STCorrectionTransactionAvg](@fDate VARCHAR(10), @nFlag INT)
AS
/*
EXECUTE SpM_STCorrectionTransactionAvg '2019-04-04',0



*/

BEGIN

		   EXECUTE SpM_STGenerateAvgCost @fDate, @nFlag		

		   UPDATE A2ZSTTRANSACTION SET A2ZSTTRANSACTION.ItemUnitPrice =  
           ISNULL((SELECT STKUnitAvgCost FROM A2ZSTMST
		   WHERE A2ZSTTRANSACTION.ItemCode = A2ZSTMST.STKItemCode),0)
   		   FROM A2ZSTMST,A2ZSTTRANSACTION
		   WHERE A2ZSTMST.STKItemCode = A2ZSTTRANSACTION.ItemCode AND FuncOpt <> 1;


		   UPDATE A2ZSTTRANSACTION SET A2ZSTTRANSACTION.ItemNetCostPrice = (A2ZSTTRANSACTION.ItemPurchaseQty * round((A2ZSTTRANSACTION.ItemUnitPrice),2)) 
      	   WHERE A2ZSTTRANSACTION.FuncOpt = 11 OR A2ZSTTRANSACTION.FuncOpt = 12 OR A2ZSTTRANSACTION.FuncOpt = 13 OR (A2ZSTTRANSACTION.FuncOpt = 20 AND A2ZSTTRANSACTION.TrnQtyDr > 0);

           UPDATE A2ZSTTRANSACTION SET A2ZSTTRANSACTION.ItemTotalPrice = (A2ZSTTRANSACTION.ItemPurchaseQty * round((A2ZSTTRANSACTION.ItemUnitPrice),2)) 
      	   WHERE A2ZSTTRANSACTION.FuncOpt = 2 or A2ZSTTRANSACTION.FuncOpt = 12 or A2ZSTTRANSACTION.FuncOpt = 20;

		   UPDATE A2ZSTTRANSACTION SET A2ZSTTRANSACTION.TrnAmtCr =  A2ZSTTRANSACTION.ItemTotalPrice
      	   WHERE A2ZSTTRANSACTION.FuncOpt = 2;

		   UPDATE A2ZSTTRANSACTION SET A2ZSTTRANSACTION.TrnAmtDr =  A2ZSTTRANSACTION.ItemTotalPrice
      	   WHERE A2ZSTTRANSACTION.FuncOpt = 12 or A2ZSTTRANSACTION.FuncOpt = 20;
END



















GO

