
 UPDATE A2ZHRMCUS..A2ZEMPLOYEE SET A2ZHRMCUS..A2ZEMPLOYEE.EmpCashCode=A2ZCSMCUS..A2ZSYSIDS.GLCashCode 
FROM A2ZHRMCUS..A2ZEMPLOYEE,A2ZCSMCUS..A2ZSYSIDS
                                   WHERE A2ZHRMCUS..A2ZEMPLOYEE.EmpCode=A2ZCSMCUS..A2ZSYSIDS.EmpCode; 