USE [A2ZCSMCUS]
GO

/****** Object:  Table [dbo].[WFA2ZERPMODULE]    Script Date: 07/16/2018 10:24:18 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[WFA2ZERPMODULE](
	[ModuleNo] [tinyint] NOT NULL,
	[ModuleName] [nvarchar](40) NULL,
 CONSTRAINT [PK_WFA2ZERPMODULE] PRIMARY KEY CLUSTERED 
(
	[ModuleNo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

