USE [A2ZCSMCUS]
GO

/****** Object:  Table [dbo].[WFA2ZTRANSACTION]    Script Date: 05/29/2018 1:13:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[WFA2ZTRANSACTION](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[BatchNo] [int] NULL,
	[TrnDate] [smalldatetime] NULL,
	[VchNo] [nvarchar](20) NULL,
	[VoucherNo] [nvarchar](20) NULL,
	[CuType] [smallint] NULL,
	[CuNo] [int] NULL,
	[MemNo] [int] NULL,
	[AccType] [int] NULL,
	[AccNo] [bigint] NULL,
	[TrnCode] [int] NULL,
	[FuncOpt] [smallint] NULL,
	[FuncOptDesc] [nvarchar](100) NULL,
	[PayType] [int] NULL,
	[TrnType] [tinyint] NULL,
	[TrnDrCr] [tinyint] NULL,
	[TrnDebit] [money] NULL,
	[TrnCredit] [money] NULL,
	[TrnDesc] [nvarchar](50) NULL,
	[TrnVchType] [nvarchar](1) NULL,
	[TrnChqPrx] [nvarchar](7) NULL,
	[TrnChqNo] [nvarchar](15) NULL,
	[ShowInterest] [tinyint] NULL,
	[TrnInterestAmt] [money] NULL,
	[TrnPenalAmt] [money] NULL,
	[TrnChargeAmT] [money] NULL,
	[TrnDueIntAmt] [money] NULL,
	[TrnODAmount] [money] NULL,
	[BranchNo] [int] NULL,
	[TrnCSGL] [tinyint] NULL,
	[TrnGLAccNoDr] [int] NULL,
	[TrnGLAccNoCr] [int] NULL,
	[TrnGLFlag] [tinyint] NULL,
	[GLAccNo] [int] NULL,
	[GLAmount] [money] NULL,
	[GLDebitAmt] [money] NULL,
	[GLCreditAmt] [money] NULL,
	[TrnFlag] [tinyint] NULL,
	[TrnStatus] [tinyint] NULL,
	[FromCashCode] [int] NULL,
	[TrnProcStat] [tinyint] NULL,
	[TrnSysUser] [tinyint] NULL,
	[TrnModule] [tinyint] NULL,
	[ValueDate] [smalldatetime] NULL,
	[UserIP] [nvarchar](50) NULL,
	[UserID] [int] NULL,
	[VerifyUserID] [int] NULL,
	[CreateDate] [datetime] NULL,
 CONSTRAINT [PK_WFA2ZTRANSACTION] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[WFA2ZTRANSACTION] ADD  CONSTRAINT [DF_WFA2ZTRANSACTION_BatchNo]  DEFAULT ((0)) FOR [BatchNo]
GO

ALTER TABLE [dbo].[WFA2ZTRANSACTION] ADD  CONSTRAINT [DF_WFA2ZTRANSACTION_CuType]  DEFAULT ((0)) FOR [CuType]
GO

ALTER TABLE [dbo].[WFA2ZTRANSACTION] ADD  CONSTRAINT [DF_WFA2ZTRANSACTION_CuNo]  DEFAULT ((0)) FOR [CuNo]
GO

ALTER TABLE [dbo].[WFA2ZTRANSACTION] ADD  CONSTRAINT [DF_WFA2ZTRANSACTION_MemNo]  DEFAULT ((0)) FOR [MemNo]
GO

ALTER TABLE [dbo].[WFA2ZTRANSACTION] ADD  CONSTRAINT [DF_WFA2ZTRANSACTION_AccType]  DEFAULT ((0)) FOR [AccType]
GO

ALTER TABLE [dbo].[WFA2ZTRANSACTION] ADD  CONSTRAINT [DF_WFA2ZTRANSACTION_AccNo]  DEFAULT ((0)) FOR [AccNo]
GO

ALTER TABLE [dbo].[WFA2ZTRANSACTION] ADD  CONSTRAINT [DF_WFA2ZTRANSACTION_FuncOpt]  DEFAULT ((0)) FOR [FuncOpt]
GO

ALTER TABLE [dbo].[WFA2ZTRANSACTION] ADD  CONSTRAINT [DF_WFA2ZTRANSACTION_PayType]  DEFAULT ((0)) FOR [PayType]
GO

ALTER TABLE [dbo].[WFA2ZTRANSACTION] ADD  CONSTRAINT [DF_WFA2ZTRANSACTION_TrnType]  DEFAULT ((0)) FOR [TrnType]
GO

ALTER TABLE [dbo].[WFA2ZTRANSACTION] ADD  CONSTRAINT [DF_WFA2ZTRANSACTION_TrnDrCr]  DEFAULT ((0)) FOR [TrnDrCr]
GO

ALTER TABLE [dbo].[WFA2ZTRANSACTION] ADD  CONSTRAINT [DF_WFA2ZTRANSACTION_TrnDebit]  DEFAULT ((0)) FOR [TrnDebit]
GO

ALTER TABLE [dbo].[WFA2ZTRANSACTION] ADD  CONSTRAINT [DF_WFA2ZTRANSACTION_TrnCredit]  DEFAULT ((0)) FOR [TrnCredit]
GO

ALTER TABLE [dbo].[WFA2ZTRANSACTION] ADD  CONSTRAINT [DF_WFA2ZTRANSACTION_TrnChqNo]  DEFAULT ((0)) FOR [TrnChqNo]
GO

ALTER TABLE [dbo].[WFA2ZTRANSACTION] ADD  CONSTRAINT [DF_WFA2ZTRANSACTION_ShowInterest]  DEFAULT ((0)) FOR [ShowInterest]
GO

ALTER TABLE [dbo].[WFA2ZTRANSACTION] ADD  CONSTRAINT [DF_WFA2ZTRANSACTION_TrnInterestAmt]  DEFAULT ((0)) FOR [TrnInterestAmt]
GO

ALTER TABLE [dbo].[WFA2ZTRANSACTION] ADD  CONSTRAINT [DF_WFA2ZTRANSACTION_TrnPenalAmt]  DEFAULT ((0)) FOR [TrnPenalAmt]
GO

ALTER TABLE [dbo].[WFA2ZTRANSACTION] ADD  CONSTRAINT [DF_WFA2ZTRANSACTION_TrnChargeAmT]  DEFAULT ((0)) FOR [TrnChargeAmT]
GO

ALTER TABLE [dbo].[WFA2ZTRANSACTION] ADD  CONSTRAINT [DF_WFA2ZTRANSACTION_TrnDueIntAmt]  DEFAULT ((0)) FOR [TrnDueIntAmt]
GO

ALTER TABLE [dbo].[WFA2ZTRANSACTION] ADD  CONSTRAINT [DF_WFA2ZTRANSACTION_TrnODAmount]  DEFAULT ((0)) FOR [TrnODAmount]
GO

ALTER TABLE [dbo].[WFA2ZTRANSACTION] ADD  CONSTRAINT [DF_WFA2ZTRANSACTION_BranchNo]  DEFAULT ((0)) FOR [BranchNo]
GO

ALTER TABLE [dbo].[WFA2ZTRANSACTION] ADD  CONSTRAINT [DF_WFA2ZTRANSACTION_TrnCSGL]  DEFAULT ((0)) FOR [TrnCSGL]
GO

ALTER TABLE [dbo].[WFA2ZTRANSACTION] ADD  CONSTRAINT [DF_WFA2ZTRANSACTION_TrnGLAccNoDr]  DEFAULT ((0)) FOR [TrnGLAccNoDr]
GO

ALTER TABLE [dbo].[WFA2ZTRANSACTION] ADD  CONSTRAINT [DF_WFA2ZTRANSACTION_TrnGLAccNoCr]  DEFAULT ((0)) FOR [TrnGLAccNoCr]
GO

ALTER TABLE [dbo].[WFA2ZTRANSACTION] ADD  CONSTRAINT [DF_WFA2ZTRANSACTION_TrnGLFlag]  DEFAULT ((0)) FOR [TrnGLFlag]
GO

ALTER TABLE [dbo].[WFA2ZTRANSACTION] ADD  CONSTRAINT [DF_WFA2ZTRANSACTION_GLAccNo]  DEFAULT ((0)) FOR [GLAccNo]
GO

ALTER TABLE [dbo].[WFA2ZTRANSACTION] ADD  CONSTRAINT [DF_WFA2ZTRANSACTION_GLAmount]  DEFAULT ((0)) FOR [GLAmount]
GO

ALTER TABLE [dbo].[WFA2ZTRANSACTION] ADD  CONSTRAINT [DF_WFA2ZTRANSACTION_GLDebitAmt]  DEFAULT ((0)) FOR [GLDebitAmt]
GO

ALTER TABLE [dbo].[WFA2ZTRANSACTION] ADD  CONSTRAINT [DF_WFA2ZTRANSACTION_GLCreditAmt]  DEFAULT ((0)) FOR [GLCreditAmt]
GO

ALTER TABLE [dbo].[WFA2ZTRANSACTION] ADD  CONSTRAINT [DF_WFA2ZTRANSACTION_TrnFlag]  DEFAULT ((0)) FOR [TrnFlag]
GO

ALTER TABLE [dbo].[WFA2ZTRANSACTION] ADD  CONSTRAINT [DF_WFA2ZTRANSACTION_TrnStatus]  DEFAULT ((0)) FOR [TrnStatus]
GO

ALTER TABLE [dbo].[WFA2ZTRANSACTION] ADD  CONSTRAINT [DF_WFA2ZTRANSACTION_FromCashCode]  DEFAULT ((0)) FOR [FromCashCode]
GO

ALTER TABLE [dbo].[WFA2ZTRANSACTION] ADD  CONSTRAINT [DF_WFA2ZTRANSACTION_TrnProcStat]  DEFAULT ((0)) FOR [TrnProcStat]
GO

ALTER TABLE [dbo].[WFA2ZTRANSACTION] ADD  CONSTRAINT [DF_WFA2ZTRANSACTION_TrnSysUser]  DEFAULT ((0)) FOR [TrnSysUser]
GO

ALTER TABLE [dbo].[WFA2ZTRANSACTION] ADD  CONSTRAINT [DF_WFA2ZTRANSACTION_UserID]  DEFAULT ((0)) FOR [UserID]
GO

ALTER TABLE [dbo].[WFA2ZTRANSACTION] ADD  CONSTRAINT [DF_WFA2ZTRANSACTION_VerifyUserID]  DEFAULT ((0)) FOR [VerifyUserID]
GO

