USE [A2ZCSMCUS]
GO

/****** Object:  Table [dbo].[WFCSLEDGERBALANCE]    Script Date: 05/28/2018 2:44:04 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[WFCSLEDGERBALANCE](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CuType] [smallint] NULL,
	[CuNo] [int] NULL,
	[MemNo] [int] NULL,
	[MemName] [nvarchar](100) NULL,
	[AccNo] [nvarchar](16) NULL,
	[OpenDate] [smalldatetime] NULL,
	[Status] [nvarchar](50) NULL,
	[LastTrnDate] [smalldatetime] NULL,
	[Balance] [money] NOT NULL,
	[AccType] [tinyint] NULL,
	[AccStatus] [tinyint] NULL,
	[GLCashCode] [int] NULL,
	[AccStatusDate] [smalldatetime] NULL,
	[OwnBalance] [money] NULL,
	[OfficeBalance] [money] NULL,
	[IntBalance] [money] NULL,
	[AccOpBal] [money] NULL,
	[AccDRBal] [money] NULL,
	[AccCRBal] [money] NULL,
	[AccCloBal] [money] NULL,
 CONSTRAINT [PK_WFCSLEDGERBALANCE] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[WFCSLEDGERBALANCE] ADD  CONSTRAINT [DF_WFCSLEDGERBALANCE_DepositeAmt]  DEFAULT ((0)) FOR [CuNo]
GO

ALTER TABLE [dbo].[WFCSLEDGERBALANCE] ADD  CONSTRAINT [DF_WFCSLEDGERBALANCE_Period]  DEFAULT ((0)) FOR [MemNo]
GO

ALTER TABLE [dbo].[WFCSLEDGERBALANCE] ADD  CONSTRAINT [DF_WFCSLEDGERBALANCE_MaturedAmt]  DEFAULT ((0)) FOR [MemName]
GO

ALTER TABLE [dbo].[WFCSLEDGERBALANCE] ADD  CONSTRAINT [DF_WFCSLEDGERBALANCE_IntRate]  DEFAULT ((0)) FOR [AccNo]
GO

ALTER TABLE [dbo].[WFCSLEDGERBALANCE] ADD  CONSTRAINT [DF_WFCSLEDGERBALANCE_PenalAmt]  DEFAULT ((0)) FOR [OpenDate]
GO

ALTER TABLE [dbo].[WFCSLEDGERBALANCE] ADD  CONSTRAINT [DF_WFCSLEDGERBALANCE_BonusAmt]  DEFAULT ((0)) FOR [Status]
GO

ALTER TABLE [dbo].[WFCSLEDGERBALANCE] ADD  CONSTRAINT [DF_WFCSLEDGERBALANCE_AccOpBal]  DEFAULT ((0)) FOR [AccOpBal]
GO

ALTER TABLE [dbo].[WFCSLEDGERBALANCE] ADD  CONSTRAINT [DF_WFCSLEDGERBALANCE_AccDRBal]  DEFAULT ((0)) FOR [AccDRBal]
GO

ALTER TABLE [dbo].[WFCSLEDGERBALANCE] ADD  CONSTRAINT [DF_WFCSLEDGERBALANCE_AccCRBal]  DEFAULT ((0)) FOR [AccCRBal]
GO

ALTER TABLE [dbo].[WFCSLEDGERBALANCE] ADD  CONSTRAINT [DF_WFCSLEDGERBALANCE_AccCloBal]  DEFAULT ((0)) FOR [AccCloBal]
GO

