USE [A2ZSTMCUST2018]
GO

/****** Object:  Table [dbo].[A2ZSTSUPPOPBAL]    Script Date: 6/23/2018 10:20:31 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[A2ZSTSUPPOPBAL](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[STKSuppCode] [int] NULL,
	[STKSuppBalance] [money] NULL,
	[STKSuppVATAmt] [money] NULL,
	[STKSuppTAXAmt] [money] NULL,
 CONSTRAINT [PK_A2ZSTSUPPOPBAL] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

