USE A2ZCSMCUS
GO
TRUNCATE TABLE A2ZTRANSACTION
GO
TRUNCATE TABLE WFCSANNIVERSARY6YR
GO
TRUNCATE TABLE WFCSANNIVERSARYFDR
GO
TRUNCATE TABLE WFCSPROVISION6YR
GO
TRUNCATE TABLE WFCSPROVISIONFDR
GO
TRUNCATE TABLE WFCSPROVISIONMSPLUS
GO
TRUNCATE TABLE WFCSRENEW6YR
GO
TRUNCATE TABLE WFCSRENEWFDR
GO
TRUNCATE TABLE WFCSRENEWBENEFIT

