USE [A2ZSTMCUS]
GO

/****** Object:  Table [dbo].[A2ZGROUP]    Script Date: 6/23/2018 10:01:44 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[A2ZGROUP](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[GrpCode] [int] NULL,
	[GrpDescription] [nvarchar](50) NULL,
 CONSTRAINT [PK_A2ZGROUP] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[A2ZGROUP] ADD  CONSTRAINT [DF_GROUP_GrpCode]  DEFAULT ((0)) FOR [GrpCode]
GO

