USE [A2ZSTMCUS]
GO

/****** Object:  Table [dbo].[A2ZSUBGROUP]    Script Date: 6/23/2018 10:02:44 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[A2ZSUBGROUP](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[GrpCode] [int] NULL,
	[SubGrpCode] [int] NULL,
	[SubGrpDescription] [nvarchar](50) NULL,
	[LastRec] [int] NULL,
 CONSTRAINT [PK_A2ZSUBGROUP] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[A2ZSUBGROUP] ADD  CONSTRAINT [DF_A2ZSUBGROUP_GrpCode]  DEFAULT ((0)) FOR [GrpCode]
GO

ALTER TABLE [dbo].[A2ZSUBGROUP] ADD  CONSTRAINT [DF_A2ZSUBGROUP_SubGrpCode]  DEFAULT ((0)) FOR [SubGrpCode]
GO

ALTER TABLE [dbo].[A2ZSUBGROUP] ADD  CONSTRAINT [DF_A2ZSUBGROUP_LastRec]  DEFAULT ((0)) FOR [LastRec]
GO

