USE [A2ZSTMCUS]
GO

/****** Object:  Table [dbo].[A2ZSTCHRG]    Script Date: 6/23/2018 10:01:52 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[A2ZSTCHRG](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[STKVat] [float] NULL,
	[STKTax] [float] NULL,
 CONSTRAINT [PK_A2ZSTCHRG] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

