USE [A2ZSTMCUS]
GO

/****** Object:  Table [dbo].[A2ZTRNFUNCOPT]    Script Date: 6/23/2018 10:03:10 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[A2ZTRNFUNCOPT](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FuncOpt] [int] NULL,
	[FuncOptDesc] [nvarchar](50) NULL,
 CONSTRAINT [PK_A2ZTRNFUNCOPT] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

