USE [A2ZSTMCUS]
GO

/****** Object:  Table [dbo].[A2ZWAREHOUSE]    Script Date: 6/23/2018 10:03:30 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[A2ZWAREHOUSE](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[WaseCode] [int] NULL,
	[WaseDescription] [nvarchar](50) NULL,
 CONSTRAINT [PK_A2ZWAREHOUSE] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[A2ZWAREHOUSE] ADD  CONSTRAINT [DF_A2ZWAREHOUSE_WaseCode]  DEFAULT ((0)) FOR [WaseCode]
GO

