USE [A2ZSTMCUS]
GO

/****** Object:  Table [dbo].[WFSTSTATEMENT]    Script Date: 6/23/2018 10:04:31 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[WFSTSTATEMENT](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[TrnDate] [smalldatetime] NULL,
	[VchNo] [nvarchar](20) NULL,
	[VoucherNo] [nvarchar](20) NULL,
	[ItemCode] [int] NULL,
	[ItemName] [nvarchar](50) NULL,
	[TrnType] [tinyint] NULL,
	[TrnQtyDebit] [int] NULL,
	[TrnQtyCredit] [int] NULL,
	[TrnDesc] [nvarchar](100) NULL,
	[TrnProcStat] [tinyint] NULL,
	[UserID] [int] NULL,
	[CreateDate] [datetime] NULL,
 CONSTRAINT [PK_WFSTSTATEMENT] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[WFSTSTATEMENT] ADD  CONSTRAINT [DF_WFSTSTATEMENT_TrnType]  DEFAULT ((0)) FOR [TrnType]
GO

ALTER TABLE [dbo].[WFSTSTATEMENT] ADD  CONSTRAINT [DF_WFSTSTATEMENT_TrnDebit]  DEFAULT ((0)) FOR [TrnQtyDebit]
GO

ALTER TABLE [dbo].[WFSTSTATEMENT] ADD  CONSTRAINT [DF_WFSTSTATEMENT_TrnCredit]  DEFAULT ((0)) FOR [TrnQtyCredit]
GO

ALTER TABLE [dbo].[WFSTSTATEMENT] ADD  CONSTRAINT [DF_WFSTSTATEMENT_TrnProcStat]  DEFAULT ((0)) FOR [TrnProcStat]
GO

ALTER TABLE [dbo].[WFSTSTATEMENT] ADD  CONSTRAINT [DF_WFSTSTATEMENT_UserID]  DEFAULT ((0)) FOR [UserID]
GO

