USE [A2ZSTMCUS]
GO

/****** Object:  Table [dbo].[WFSTLEDGERBALANCE]    Script Date: 6/23/2018 10:04:19 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[WFSTLEDGERBALANCE](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[SuppCode] [int] NULL,
	[SuppName] [nvarchar](50) NULL,
	[SuppBalance] [money] NULL,
	[SuppVATAmt] [money] NULL,
	[SuppTAXAmt] [money] NULL,
 CONSTRAINT [PK_WFSTLEDGERBALANCE] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[WFSTLEDGERBALANCE] ADD  CONSTRAINT [DF_WFSTLEDGERBALANCE_SuppCode]  DEFAULT ((0)) FOR [SuppCode]
GO

