USE [A2ZSTMCUS]
GO

/****** Object:  Table [dbo].[WFSTSUPPSTATEMENT]    Script Date: 6/23/2018 10:04:44 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[WFSTSUPPSTATEMENT](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[TrnDate] [smalldatetime] NULL,
	[VchNo] [nvarchar](20) NULL,
	[VoucherNo] [nvarchar](20) NULL,
	[SuppCode] [int] NULL,
	[SuppName] [nvarchar](50) NULL,
	[TrnType] [tinyint] NULL,
	[TrnAmtDebit] [int] NULL,
	[TrnAmtCredit] [int] NULL,
	[TrnDesc] [nvarchar](100) NULL,
	[TrnProcStat] [tinyint] NULL,
	[UserID] [int] NULL,
	[CreateDate] [datetime] NULL,
 CONSTRAINT [PK_WFSTSUPPSTATEMENT] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[WFSTSUPPSTATEMENT] ADD  CONSTRAINT [DF_WFSTSUPPSTATEMENT_TrnType]  DEFAULT ((0)) FOR [TrnType]
GO

ALTER TABLE [dbo].[WFSTSUPPSTATEMENT] ADD  CONSTRAINT [DF_WFSTSUPPSTATEMENT_TrnDebit]  DEFAULT ((0)) FOR [TrnAmtDebit]
GO

ALTER TABLE [dbo].[WFSTSUPPSTATEMENT] ADD  CONSTRAINT [DF_WFSTSUPPSTATEMENT_TrnCredit]  DEFAULT ((0)) FOR [TrnAmtCredit]
GO

ALTER TABLE [dbo].[WFSTSUPPSTATEMENT] ADD  CONSTRAINT [DF_WFSTSUPPSTATEMENT_TrnProcStat]  DEFAULT ((0)) FOR [TrnProcStat]
GO

ALTER TABLE [dbo].[WFSTSUPPSTATEMENT] ADD  CONSTRAINT [DF_WFSTSUPPSTATEMENT_UserID]  DEFAULT ((0)) FOR [UserID]
GO

